version: 2
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup'
          command: |
            uv venv --python 3.9 ~/.virtualenvs/tap-shippo
            source ~/.virtualenvs/tap-shippo/bin/activate
            uv pip install .
            uv pip install pylint
      - run:
          name: 'Pylint'
          command: |
            source ~/.virtualenvs/tap-shippo/bin/activate
            pylint tap_shippo -r n -d missing-docstring,locally-disabled,consider-using-f-string,broad-exception-raised

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
